name: Build, lint and test

on:
    # Triggers the workflow on push or pull request events but only for the main branch and release branches
    push:
        branches: [main, release**]
    pull_request:
        branches: [main, release**]

    # Allows us to run the workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    dependencies:
        runs-on: ubuntu-20.04

        steps:
            - uses: actions/checkout@v2

            - name: Cache dependencies
              id: fetch-dependencies
              uses: actions/cache@v2
              with:
                  path: |
                      **/node_modules
                  key: ${{ runner.os }}-v3-${{ hashFiles('**/yarn.lock') }}

            - uses: actions/setup-node@v2
              if: steps.fetch-dependencies.outputs.cache-hit != 'true'
              with:
                  node-version: '14.16.0'

            - name: Download dependencies
              if: steps.fetch-dependencies.outputs.cache-hit != 'true'
              run: yarn

    build:
        runs-on: ubuntu-20.04
        needs: [dependencies]

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '14.16.0'

            - name: Get cached dependencies
              uses: actions/cache@v2
              with:
                  path: |
                      **/node_modules
                  key: ${{ runner.os }}-v3-${{ hashFiles('**/yarn.lock') }}

            - name: Build
              run: yarn build:dev

            - name: Save build artifacts in cache
              uses: actions/cache@v2
              with:
                  path: |
                      **/build
                      **/dist
                  key: ${{ runner.os }}-v3-${{ hashFiles('**/build/', '**/dist/') }}

    build-piggybank:
        runs-on: ubuntu-20.04
        needs: [dependencies]
        defaults:
            run:
                working-directory: examples/piggybank

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '14.16.0'

            - name: Get cached dependencies
              uses: actions/cache@v2
              with:
                  path: |
                      **/node_modules
                  key: ${{ runner.os }}-v3-${{ hashFiles('**/yarn.lock') }}

            - name: Build
              run: yarn build

            - name: Save build artifacts in cache
              uses: actions/cache@v2
              with:
                  path: |
                      **/build
                      **/dist
                  key: ${{ runner.os }}-v3-${{ hashFiles('**/build/', '**/dist/') }}

    type-test-piggybank:
        runs-on: ubuntu-20.04
        needs: [build-piggybank]
        defaults:
            run:
                working-directory: examples/piggybank

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '14.16.0'

            - name: Get cached dependencies
              uses: actions/cache@v2
              with:
                  path: |
                      **/node_modules
                  key: ${{ runner.os }}-v3-${{ hashFiles('**/yarn.lock') }}

            - name: TypeCheck
              run: yarn tsc --noEmit

            - name: Save build artifacts in cache
              uses: actions/cache@v2
              with:
                  path: |
                      **/build
                      **/dist
                  key: ${{ runner.os }}-v3-${{ hashFiles('**/build/', '**/dist/') }}

    lint:
        runs-on: ubuntu-20.04
        needs: [build]

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '14.16.0'

            - name: Get cached dependencies
              uses: actions/cache@v2
              with:
                  path: |
                      **/node_modules
                  key: ${{ runner.os }}-v3-${{ hashFiles('**/yarn.lock') }}

            - name: Get build cache
              uses: actions/cache@v2
              with:
                  path: |
                      **/build
                      **/dist
                  key: ${{ runner.os }}-v3-${{ hashFiles('**/build/', '**/dist/') }}

            - name: Lint
              run: yarn lint

    type-check:
        runs-on: ubuntu-20.04
        needs: [build]

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '14.16.0'

            - name: Get cached dependencies
              uses: actions/cache@v2
              with:
                  path: |
                      **/node_modules
                  key: ${{ runner.os }}-v3-${{ hashFiles('**/yarn.lock') }}

            - name: Get build cache
              uses: actions/cache@v2
              with:
                  path: |
                      **/build
                      **/dist
                  key: ${{ runner.os }}-v3-${{ hashFiles('**/build/', '**/dist/') }}

            - name: TypeCheck
              run: yarn type:check

    test:
        runs-on: ubuntu-20.04
        needs: [build]

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '14.16.0'

            - name: Get cached dependencies
              uses: actions/cache@v2
              with:
                  path: |
                      **/node_modules
                  key: ${{ runner.os }}-v3-${{ hashFiles('**/yarn.lock') }}

            - name: Get build cache
              uses: actions/cache@v2
              with:
                  path: |
                      **/build
                      **/dist
                  key: ${{ runner.os }}-v3-${{ hashFiles('**/build/', '**/dist/') }}

            - name: Test
              run: yarn test
