on:
  push:
    tags:
      - dapp-wccd/*

env:
  BASE_IMAGE: "node:18-slim"

jobs:
  release-docker:
    runs-on: ubuntu-latest
    environment: release
    strategy:
      fail-fast: false
      matrix:
        env:
          - "testnet"
          - "mainnet"
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: 'concordium'
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Clone repo
        uses: actions/checkout@v4

      - name: Set image tag if correctly formatted
        env:
          TAG: ${{ github.ref_name }}
        run: |
          TAG_VERSION=${{ matrix.env }}-${TAG##${{ inputs.SERVICE_NAME }}/}
          echo "FULL_IMAGE_TAG=concordium/${{ inputs.SERVICE_NAME }}:${TAG_VERSION}" >> $GITHUB_ENV

      - name: Check if image exist
        run: |
          set +e
          docker manifest inspect ${{ env.FULL_IMAGE_TAG }}
          EXITCODE=$?
          if [ $EXITCODE -eq "0" ]; then
            echo "Error: ${{ env.FULL_IMAGE_TAG }} already exist"
            exit 1
          fi

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./examples/wCCD/Dockerfile
          tags: ${{ env.FULL_IMAGE_TAG }}
          no-cache: true
          push: true
          build-args: |
            base_image=${{ env.BASE_IMAGE }}
            NETWORK=${{ matrix.env }}
