on:
  push:
    tags:
      - dapp-esealing/*

jobs:
  release-base-image:
    uses: concordium/.github/.github/workflows/docker-release-workflow.yaml@v1
    with:
      SERVICE_NAME: "dapp-esealing"
      BUILD_ARGS: |
        base_image=node:18-slim
      DOCKER_FILE_PATH: examples/eSealing
    secrets: inherit
